apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: bank-vault
spec:
  size: 3
  image: vault:1.2.3
  bankVaultsImage: banzaicloud/bank-vaults:0.5.3

  ########## Kubernetes configuration ##########
  annotations: {}                 # Common annotations for all created resources
  vaultAnnotations: {}            # Vault Pods, Services and TLS Secret annotations
  vaultConfigurerAnnotations: {}  # VaultConfigurer Pods and Services annotations
  vaultLabels: {}                 # Vault Pods, Services and TLS Secret labels
  vaultConfigurerLabels: {}       # VaultConfigurer Pods and Services labels

  vaultPodSpec:
    # priorityClassName: high-priority
  vaultConfigurerPodSpec:
    # priorityClassName: high-priority

  resources:
    vault: {}
    bankVaults: {}
    prometheusExporter: {}

  podAntiAffinity: # topologyKey used by podAntiAffinity
  nodeAffinity: {}
  nodeSelector: {}
  tolerations: []

  serviceAccount: vault

  serviceType: ClusterIP
  ingress:
    annotations:
    spec: {}

  envsConfig: []
  vaultEnvsConfig: []
  credentialsConfig: {}
  volumes: []
  volumeMounts: []
  volumeClaimTemplates: []

  ########## Etcd configuration ##########
  # See: https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-etcd-ha.yaml
  # etcdSize: 1
  # etcdPVCSpec:
  # etcdAnnotations:
  # etcdPodAnnotations:

  ########## Fluentd configuration ##########
  # See: https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-audit.yaml
  # fluentdEnabled: true
  # fluentdImage: banzaicloud/fluentd-s3:latest
  # fluentdConfig:

  ########## Vault configuration ##########
  statsdDisabled: false
  caNamespaces: []
  # # Optionally Watch for the cert-manager managed secret and trigger restart of Vault when the secret change
  # watchedSecretsLabels:
  # - certmanager.k8s.io/certificate-name: <cert-manager-tls-secret-name>

  # A YAML representation of a final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  # Use "${ .Env.VARIABLE_NAME }" for environment interpolation
  config: {}

  # Describe where you would like to store the Vault unseal keys and root token.
  unsealConfig:
    options:
      # The preFlightChecks flag enables unseal and root token storage tests
      # This is true by default
      preFlightChecks: true
    kubernetes:
      secretNamespace: bank-vault

  # See https://github.com/banzaicloud/bank-vaults/blob/master/docs/cli-tool/README.md#example-external-vault-configuration
  externalConfig:
    policies: []
    auth: []
    secrets: []
    plugins: []
    audit: []
    startupSecrets: []
