apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: foo.bar
spec:
  secretName: foo.bar-tls
  duration: 2160h     # 90d
  renewBefore: 360h   # 15d
  commonName: foo.bar
  dnsNames:
  - foo.bar
  - www.foo.bar
  issuerRef:
    name: ca-issuer
    kind: Issuer

# Issuing Certificates
# ref: https://cert-manager.io/docs/usage/certificate/
